-- Migração: tabelas de cache SAP + campos adicionais para integração bidirecional
-- Execute no SQL Editor do Supabase ANTES de ativar a integração SAP.
--
-- FLUXO:
--   Edge Function sync-mestres-sap (cron a cada 2 min)
--     └─ puxa do SAP Gateway → grava em locais_instalacao / equipamentos / sintomas_catalogo
--   Formulário nova SAF (usuário)
--     └─ lê de locais_instalacao / equipamentos / sintomas_catalogo  (NUNCA chama o SAP direto)
--   CCM aprova → Flask chama sap_criar_nota() → grava QMNUM em saf_integracao_sap

-- ═══════════════════════════════════════════════════════════════
-- PARTE 1: TABELAS DE CACHE DE DADOS MESTRES DO SAP
-- Estas tabelas são preenchidas pela Edge Function e lidas pelo
-- formulário de nova SAF. O usuário nunca vê o SAP diretamente.
-- ═══════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────
-- 1a. Locais de Instalação (TPLNR / transação IL03 no SAP)
--     Cache de todos os locais ativos cadastrados no SAP.
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.locais_instalacao (
  id              bigint generated by default as identity primary key,
  -- Código técnico SAP (TPLNR), ex: "BR-SP-PLANTA01-AREA02"
  codigo          text not null unique,
  descricao       text not null,
  ativo           boolean not null default true,
  -- Preenchido pela Edge Function a cada sincronização
  sincronizado_em timestamptz,
  criado_em       timestamptz not null default now(),
  atualizado_em   timestamptz not null default now()
);

COMMENT ON TABLE  public.locais_instalacao IS 'Cache de Locais de Instalação ativos do SAP (TPLNR). Atualizado pela Edge Function sync-mestres-sap.';
DO $$ BEGIN
  COMMENT ON COLUMN public.locais_instalacao.codigo IS 'Código técnico SAP do Local de Instalação (TPLNR).';
EXCEPTION WHEN undefined_column OR undefined_table THEN NULL; END $$;
DO $$ BEGIN
  COMMENT ON COLUMN public.locais_instalacao.sincronizado_em IS 'Última sincronização com o SAP via Edge Function.';
EXCEPTION WHEN undefined_column OR undefined_table THEN NULL; END $$;

-- ───────────────────────────────────────────────────────────────
-- 1b. Equipamentos (EQUNR / transação IE03 no SAP)
--     Cada equipamento pertence a um Local de Instalação.
--     O formulário filtra por local selecionado (hierarquia SAP).
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.equipamentos (
  id                   bigint generated by default as identity primary key,
  -- Código técnico SAP (EQUNR), ex: "10000042"
  codigo               text not null unique,
  descricao            text not null,
  -- FK para o cache de locais — permite filtrar ao selecionar local
  local_instalacao_id  bigint references public.locais_instalacao(id)
                         on update cascade on delete set null,
  ativo                boolean not null default true,
  sincronizado_em      timestamptz,
  criado_em            timestamptz not null default now(),
  atualizado_em        timestamptz not null default now()
);

COMMENT ON TABLE  public.equipamentos IS 'Cache de Equipamentos do SAP (EQUNR). Filtrado por Local de Instalação no formulário.';
DO $$ BEGIN
  COMMENT ON COLUMN public.equipamentos.codigo IS 'Código técnico SAP do Equipamento (EQUNR).';
EXCEPTION WHEN undefined_column OR undefined_table THEN NULL; END $$;
DO $$ BEGIN
  COMMENT ON COLUMN public.equipamentos.local_instalacao_id IS 'FK para locais_instalacao — define a hierarquia SAP.';
EXCEPTION WHEN undefined_column OR undefined_table THEN NULL; END $$;
DO $$ BEGIN
  COMMENT ON COLUMN public.equipamentos.sincronizado_em IS 'Última sincronização com o SAP via Edge Function.';
EXCEPTION WHEN undefined_column OR undefined_table THEN NULL; END $$;

-- ───────────────────────────────────────────────────────────────
-- 1c. Catálogo de Sintomas/Danos (Catálogo Tipo C do SAP)
--     Campos QMGRP (grupo) + QMCOD (código) da BAPI de notificação.
--     Filtrado por equipamento selecionado para evitar erro na BAPI.
-- ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.sintomas_catalogo (
  id              bigint generated by default as identity primary key,
  -- Combinação "GRUPO-CODIGO" do catálogo SAP (QMGRP-QMCOD)
  codigo          text not null unique,
  -- Grupo do catálogo (QMGRP), ex: "EL", "ME", "HI"
  grupo           text,
  -- Código dentro do grupo (QMCOD)
  codigo_item     text,
  descricao       text not null,
  -- Tipo do catálogo SAP: "C" = Sintomas/Danos
  tipo_catalogo   text not null default 'C',
  ativo           boolean not null default true,
  sincronizado_em timestamptz,
  criado_em       timestamptz not null default now(),
  atualizado_em   timestamptz not null default now()
);

COMMENT ON TABLE  public.sintomas_catalogo IS 'Cache do Catálogo Tipo C do SAP (sintomas/danos). Campos QMGRP + QMCOD da BAPI de notificação.';
DO $$ BEGIN
  COMMENT ON COLUMN public.sintomas_catalogo.codigo IS 'Chave única: concatenação QMGRP-QMCOD, ex: "EL-001".';
EXCEPTION WHEN undefined_column OR undefined_table THEN NULL; END $$;
DO $$ BEGIN
  COMMENT ON COLUMN public.sintomas_catalogo.grupo IS 'Grupo do catálogo SAP (QMGRP).';
EXCEPTION WHEN undefined_column OR undefined_table THEN NULL; END $$;
DO $$ BEGIN
  COMMENT ON COLUMN public.sintomas_catalogo.codigo_item IS 'Código dentro do grupo (QMCOD).';
EXCEPTION WHEN undefined_column OR undefined_table THEN NULL; END $$;
DO $$ BEGIN
  COMMENT ON COLUMN public.sintomas_catalogo.sincronizado_em IS 'Última sincronização com o SAP via Edge Function.';
EXCEPTION WHEN undefined_column OR undefined_table THEN NULL; END $$;

-- ═══════════════════════════════════════════════════════════════
-- PARTE 2: CAMPOS ADICIONAIS EM TABELAS JÁ EXISTENTES
-- Execute apenas se as tabelas já existem no Supabase.
-- ═══════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────
-- 2a. Enriquece locais_instalacao se já existia sem as colunas SAP
-- ───────────────────────────────────────────────────────────────
ALTER TABLE public.locais_instalacao
  ADD COLUMN IF NOT EXISTS codigo          text,
  ADD COLUMN IF NOT EXISTS ativo           boolean not null default true,
  ADD COLUMN IF NOT EXISTS sincronizado_em timestamptz;

-- id_sap é chave primária nas tabelas criadas manualmente — não pode ser alterado.
-- O seed deve fornecer um valor para id_sap.

-- UNIQUE em codigo (ignorado se já existir)
DO $$ BEGIN
  ALTER TABLE public.locais_instalacao
    ADD CONSTRAINT locais_instalacao_codigo_key UNIQUE (codigo);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;

-- ───────────────────────────────────────────────────────────────
-- 2b. Enriquece equipamentos se já existia sem as colunas SAP
-- ───────────────────────────────────────────────────────────────
ALTER TABLE public.equipamentos
  ADD COLUMN IF NOT EXISTS codigo             text,
  ADD COLUMN IF NOT EXISTS ativo              boolean not null default true,
  ADD COLUMN IF NOT EXISTS local_instalacao_id bigint,
  ADD COLUMN IF NOT EXISTS sincronizado_em    timestamptz;

-- UNIQUE em codigo (ignorado se já existir)
DO $$ BEGIN
  ALTER TABLE public.equipamentos
    ADD CONSTRAINT equipamentos_codigo_key UNIQUE (codigo);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;

-- Passo 2: adiciona a FK separadamente, ignorando se já existir ou se a ref não existir
DO $$ BEGIN
  ALTER TABLE public.equipamentos
    ADD CONSTRAINT fk_equipamentos_local
    FOREIGN KEY (local_instalacao_id)
    REFERENCES public.locais_instalacao(id)
    ON UPDATE CASCADE ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object OR undefined_column OR undefined_table THEN NULL; END $$;

-- ───────────────────────────────────────────────────────────────
-- 2c. Enriquece sintomas_catalogo: adiciona codigo, grupo, codigo_item e sincronizado_em
-- ───────────────────────────────────────────────────────────────
ALTER TABLE public.sintomas_catalogo
  ADD COLUMN IF NOT EXISTS codigo          text,
  ADD COLUMN IF NOT EXISTS grupo          text,
  ADD COLUMN IF NOT EXISTS codigo_item    text,
  ADD COLUMN IF NOT EXISTS tipo_catalogo  text not null default 'C',
  ADD COLUMN IF NOT EXISTS ativo          boolean not null default true,
  ADD COLUMN IF NOT EXISTS sincronizado_em timestamptz;

-- UNIQUE em codigo (ignorado se já existir)
DO $$ BEGIN
  ALTER TABLE public.sintomas_catalogo
    ADD CONSTRAINT sintomas_catalogo_codigo_key UNIQUE (codigo);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;

-- ───────────────────────────────────────────────────────────────
-- 2d. Campos SAP em saf_integracao_sap
-- ───────────────────────────────────────────────────────────────
ALTER TABLE public.saf_integracao_sap
  ADD COLUMN IF NOT EXISTS tipo_nota        text,   -- QMART: Z1, Z2, etc.
  ADD COLUMN IF NOT EXISTS jest_stat        text,   -- JEST-STAT (NOCO, CANCL, CLSD...)
  ADD COLUMN IF NOT EXISTS numero_ordem_sap text;   -- AUFNR: Ordem de Manutenção

COMMENT ON COLUMN public.saf_integracao_sap.tipo_nota        IS 'Tipo da Nota SAP (QMART): Z1=Corretiva Emergencial, Z2=Preventiva.';
COMMENT ON COLUMN public.saf_integracao_sap.jest_stat        IS 'Status do objeto no SAP (JEST-STAT), ex: NOCO, CANCL, CLSD.';
COMMENT ON COLUMN public.saf_integracao_sap.numero_ordem_sap IS 'Número da Ordem de Manutenção SAP (AUFNR). Quando preenchido, bloqueia cancelamento.';

-- ───────────────────────────────────────────────────────────────
-- 2e. Tipo de Nota no controle CCM (CCM define ao aprovar)
-- ───────────────────────────────────────────────────────────────
ALTER TABLE public.saf_controle_ccm
  ADD COLUMN IF NOT EXISTS tipo_nota text NOT NULL DEFAULT 'Z2';

COMMENT ON COLUMN public.saf_controle_ccm.tipo_nota IS 'Tipo da Nota SAP definido pelo CCM na aprovação. Z1=Corretiva Emergencial, Z2=Preventiva (padrão).';

-- ═══════════════════════════════════════════════════════════════
-- PARTE 3: ÍNDICES
-- ═══════════════════════════════════════════════════════════════

-- codigo (UNIQUE) e qmnum (UNIQUE) já possuem índice implícito no PostgreSQL.
-- Apenas numero_ordem_sap precisa de índice explícito.
CREATE INDEX IF NOT EXISTS idx_saf_integracao_sap_numero_ordem
  ON public.saf_integracao_sap(numero_ordem_sap);

DO $$ BEGIN
  CREATE INDEX IF NOT EXISTS idx_equipamentos_local_id
    ON public.equipamentos(local_instalacao_id);
EXCEPTION WHEN undefined_column THEN NULL; END $$;
